baseURL: "https://prodevopsguy.site/"
title: ProDevOpsGuy
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "projects"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
        - name: Projects
          url: /projects/
        - name: Telegram
          url: https://t.me/prodevopsguy

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "ProDevOpsGuy - Free DevOps/Cloud World"
  author: ProDevOpsGuy
  assets:
    favicon: "https://prodevopsguy.site/favicon.svg"
  images: ["https://prodevopsguy.site/favicon.svg"]


  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  UseHugoToc: true
  tocopen: true
  # New, from PaperModX
  TocSide: left
  # Enable KaTeX on every page globally. See blog post about setting up site
  math: true
  # comments: false
  # images: ["images/papermod-cover.png"]

  label:
    text: "Free DevOps/Cloud World"
    iconSVG: '<svg style="margin-bottom: -0.3em;border-radius: 0;" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="30" height="30"><svg width="30" height="30" viewBox="0 0 99.682 99.682" xmlns="http://www.w3.org/2000/svg"><path d="M0 10.807v78.19h46.972V73.438H15.657V57.731h23.486v-15.61H15.657V26.416h31.315v-15.61zM99.682 10.807v78.19H52.71V73.438h31.315V57.731H60.539v-15.61h23.486V26.416H52.71v-15.61z" fill="currentColor"></path></svg><style>@media (prefers-color-scheme: light) { :root { filter: none; } } </style></svg>'

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Content: |
      <div style="display: flex; align-items: center;">
          <img src="https://raw.githubusercontent.com/NotHarshhaa/ProDevOpGuy-Blog-Site/a1578a14b3a8f248abad5f0dfe08aeba736fac75/assets/images/avatar-home.png" alt="Logo" style="height:65px; width:65px; border-radius: 50%;">
          <h1 style="margin-left: 10px; font-size: 30px;">Pro DevOps Guy</h1>
      </div>

      <h3 style="font-weight: bold; margin-bottom: 20px;"> 💥 ProDevOpsGuy is a DevOps/Cloud channel which offers: 📢</h3>
      <ul>
          <li><em>Daily Trending DevOps Blogs 📑 </em></li>
          <li><em>All New Cloud Tips & Techniques 💡</em></li>
          <li><em>Realtime Interview questions ❓ & preparation guides 🗒️</em></li>
          <li><em>DevOps/Cloud Job Related Posts 💼</em></li>
          <li><em>Cloud/DevOps Related Code & Scripts 👨‍💻</em></li>
      </ul>

      <h4 style="margin-top: 20px;">❤️ Feel free to show your support by sharing with your friends and on social media.</h4>

      <h4 style="margin-top: 20px;">⚜️ Pro DevOps Guy is maintained & owned by a working DevOps Guy <a href="https://github.com/NotHarshhaa">H A R S H H A A</a>.</h4>

  socialIcons:
    - name: github
      title: View on Github
      url: "https://github.com/NotHarshhaa"
    - name: telegram
      title: Join Telegram community
      url: "https://t.me/prodevopsguy"
    - name: whatsapp
      title: Join WhatsApp community
      url: "https://chat.whatsapp.com/EEHYHnty7s8DozPtSsKYdJ"
    - name: instagram
      title: Follow on Instagram
      url: "https://instagram.com/prodevopsguy"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/harshhaareddy"

  # editPost:
  #  URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
      linkFullImages: true
      hidden: false # hide everywhere but not in structured data
      hiddenInList: false # hide on list pages and home
      hiddenInSingle: false # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
